### PR TITLE
Add ability to delete SMS message

### PR DESCRIPTION
**Pull request by davidstoneham**

### CODE REVIEW

**Comment by briankabiro** [comment]
@davidstoneham Hi, haven't yet gotten this to work on my end...
Does it work on yours?

**Comment by davidstoneham** [comment]
I've currently got it running in a app at the moment and it hasn't had any problems. I'll start an empty react project and add it and just confirm i pushed up everything. Are you getting an error is it just not returning anything?

**Comment by davidstoneham** [comment]
Ok just made a blank react native project (0.45) add my fork of the plugin and ran SmsAndroid.list and it correctly logged the messages to the console

**Comment by briankabiro** [comment]
@davidstoneham Hey, just tested it. Can we set it up such that it gives off an error if a message that someone wants to delete is missing? We could include that in the error saying the message doesn't exist. So that it says messages are deleted successfully only when a message is deleted.

**Comment by davidstoneham** [comment]
@briankabiro that shouldn't be an issue. I'll take a look when I get a moment. I've also got code to silently send messages as well (without opening the sms app and waiting for the user to press the button) that i'll integrate as well in a different pull request. Will be nice to have an all-in-one react native sms plugin finally!

**Comment by briankabiro** [comment]
@davidstoneham Okay, this looks promising

**Comment by briankabiro** [comment]
@davidstoneham Any progress?

**Comment by davidstoneham** [comment]
ok all done! The fail object will now equal SMS Not Found when you try to delete an sms that doesn't exist

**Comment by briankabiro** [comment]
@davidstoneham Okay, I'll check it out and get back to you

**Pull request merged**
