### PR TITLE
Added a functionality to send more then 160 char SMS

### PR DESCRIPTION
**Pull request by arahmanali**

### CODE REVIEW

**Comment by briankabiro** [comment]
Thanks for the contribution, @arahmanali. Going to test this out and get back

**Comment by briankabiro** [comment]
Hey @arahmanali. The logic looks fine to me. 

Is this working perfectly on your end? Yet to test it out though.

**Comment by arahmanali** [comment]
Hi @briankabiro i have tested it, in fact implemented it in our production app works fine.

**Comment by briankabiro** [comment]
Good stuff and thanks. Going to get it merged and then push a release. Will update here once that's done.

**Comment by briankabiro** [comment]
All done - Release is live under `1.3.6`

Thanks for the contribution!

**Comment by arahmanali** [comment]
great :+1:

**Pull request merged**
