### PR TITLE
Added Filter by Thread_Id

### PR DESCRIPTION
**Pull request by Windastella**
Filter by thread_id, for use case :
- listing sms conversation by threads

### CODE REVIEW

**Comment by mikehardy** [comment]
Hi there! This looks interesting, but there's nothing to help developers adopt it - or to help us prove it works now and in going forward as the library is maintained. Can you check the way the last filter addition went and think about adding to the README and the example? https://github.com/briankabiro/react-native-get-sms-android/pull/38

**Comment by Windastella** [comment]
Thank you for your reply, I will add into the README.

**Comment by Windastella** [comment]
I have updated the README:

- to show this is addition to the previous 4 filter and are OR-ed

- the filter is "thread_id"

I implemented this feature to create my own SMS messaging conversation page.

**Comment by briankabiro** [comment]
Good work, @Windastella. The code and the Readme changes seem fine to me. 

Would like to test it out first before merging and then get back.

**Comment by briankabiro** [comment]
I didn't get any issues while testing the branch. Would like to have a second pair of eyes to confirm it before merging. Have you had the chance to test it @mikehardy?

**Comment by mikehardy** [comment]
I haven't tested it and won't have time with some other deadlines I've got - but I did read through it and though it looked great. sorry!

**Comment by briankabiro** [comment]
No worries. It's also good to me. I am of the opinion that we can merge this now.

**Comment by briankabiro** [comment]
🎉  Have pushed this to npm under version 1.5.0!

Thanks for the contribution @Windastella

**Pull request merged**
